### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by derSchotte** [xmikuskad/du_calculator#2]
Hi, can you please implement other Resolutions that 1920x1080. I have a maximum Resolution of 1680x1050 and play on windowed mode by 1600x900.

thanks you

**Comment by xmikuskad** [comment]
Hello, can you please send me a screenshot with opened radar? I will see what I can do.

**Comment by xmikuskad** [comment]
Support for different resolutions and windowed mode was added in version 1.5
You can download it [here](https://github.com/xmikuskad/du_calculator/releases/tag/v1.5)

Thank you for your feedback.
