### ISSUE TITLE
Resolution >> 2560 x 1440

### ISSUE THREAD

**Issue by francois-da-dev** [xmikuskad/du_calculator#3]
Hey. 
Can you please add this resolution to the App?
What is the radar screenshot you need?

**Comment by AX3Lino** [comment]
please sent screenshot with radar fully extended (tab, left click on graph). Example ↓
![d1](https://user-images.githubusercontent.com/51678501/97187967-4b938800-17a3-11eb-92ef-0edbb5f47486.png)

**Comment by xmikuskad** [comment]
Support for different resolutions was added in version 1.5
You can download it [here](https://github.com/xmikuskad/du_calculator/releases/tag/v1.5)

Thank you for your feedback.
