### ISSUE TITLE
Resolution - 3440x1440

### ISSUE THREAD

**Issue by ErZ101** [xmikuskad/du_calculator#5]
Please add support for Ultrawide 1440p screen.  Resolution 3440x1440

**Comment by xmikuskad** [comment]
please sent screenshot with radar fully extended (tab, left click on graph). Example ↓
![image](https://user-images.githubusercontent.com/43302506/97502274-16d62b00-1973-11eb-83cd-49d9bd5ad459.png)

**Comment by xmikuskad** [comment]
please send screenshot with radar fully extended (tab, left click on graph). Example ↓
![image](https://user-images.githubusercontent.com/43302506/97502308-2d7c8200-1973-11eb-916c-dd8d378f6900.png)

**Comment by ErZ101** [comment]
Here it is
https://ibb.co/0mxj40z

**Comment by xmikuskad** [comment]
Support for different resolutions was added in version 1.5
You can download it [here](https://github.com/xmikuskad/du_calculator/releases/tag/v1.5)

Thank you for your feedback.
